### PR TITLE
Transitional syntax update

### PR DESCRIPTION
**Pull request by JoinedSenses**

### CODE REVIEW

**Comment by nefarius** [comment]
Damn! No notification on this, stellar job, GitHub! 😑 

Sorry, I don't maintain this, just mirrored it so I have no idea if this PR is valid or not.

**Comment by JoinedSenses** [comment]
Tested and verified to work correctly by myself and at least one other. I have not seen this extension maintained anywhere else. I have also received information that old syntax does not seem to work well with latest dev version of sourcemod, however the PR changes are compatible.

**Comment by JoinedSenses** [comment]
If you arent comfortable with this, I will make my own repo instead and maintain it.

**Comment by nefarius** [comment]
No worries, thanks for the update. I just haven't done anything SM related in years. But it's not that I don't wanna keep in touch 🙂

**Pull request merged**
